name: Continuous Integration
on:
  push:
    branches:
      - main
      - jenk
  workflow_dispatch:
  
jobs:
  my_first_job:
    runs-on: ubuntu-latest

    steps:
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'zulu'

    - name: Show Java version
      run: "java -version"

    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: main

    - name: Show directory
      run: 'pwd'

    - name: List files
      run: 'ls -al'

    - name: Install Dependencies
      run: 'mvn compile'

    - name: Build application
      run: 'mvn package -DskipTests'

    - name: Test application
      run: 'mvn test'

    - name: Setup SSH Key
      run: |
          mkdir -p "$HOME/.ssh"
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > "$HOME/.ssh/id_rsa"
          chmod 600 "$HOME/.ssh/id_rsa"

    - name: Deploy to Server
      run: |
         rsync --timeout=60 -e "ssh -p 22 -i $HOME/.ssh/id_rsa -o StrictHostKeyChecking=no" --archive --compress --delete target ubuntu@35.156.31.37:~/target 

    - name: Run Java application on remote machine
      run: |
        ssh -p 22 -i $HOME/.ssh/id_rsa -o StrictHostKeyChecking=no ubuntu@35.156.31.37 'timeout 30s java -jar ~/target/dev.war'
         
